# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1JArJLSjwY54kpusDLtuaniSpMxBibH
"""

#read  the dataset
import requests

proxies = {
    'http': 'http://edcguest:edcguest@172.31.100.30:3128',
    'https': 'https://edcguest:edcguest@172.31.100.30:3128',
}
import pandas as pd
#data=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRSabPFLxzD16BAbsM51VRcijU0-Oh-WomahbffWwv43OCBUfdUFRePijIP3yS9i1tc3DrltT2UHBz0/pub?output=csv")
data=pd.read_csv("comptagesvelo2015_prepared_scored - comptagesvelo2015_prepared_scored.csv")
data.head(3)

independent_variables=data.columns
independent_variables=independent_variables.delete(0)
X=data[independent_variables]
Y=data["Berri1"]
#fit the model
import sklearn.linear_model as lm
lr=lm.LinearRegression()
lr.fit(X,Y)

#PREDICT PRICE USING LINEAR REGRESSION MODEL
user_info={}
import sys
counter = 1
for feature in independent_variables:
  #temp=input("Enter the number of vehicles at street "+feature+":")    
  temp=sys.argv[counter]
  counter=counter+1
  user_info[feature]=temp     #returns a dict
  user_info_df=pd.DataFrame(data=user_info,index=[0],
                            columns=independent_variables)
price=lr.predict(user_info_df)
print("Predicted Vehicles at Berri1: ",int(round(price[0])))

